---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /guard-kubevirt-io-v1-virtualmachine
  failurePolicy: Ignore
  name: guard-virtualmachine.kb.io
  rules:
  - apiGroups:
    - kubevirt.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - virtualmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-kubevirt-ui-io-v1alpha1-managedtenant
  failurePolicy: Fail
  name: vmanagedtenant-v1alpha1.kb.io
  rules:
  - apiGroups:
    - platform.kubevirt-ui.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedtenants
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-kubevirt-ui-io-v1alpha1-managedvm
  failurePolicy: Fail
  name: vmanagedvm-v1alpha1.kb.io
  rules:
  - apiGroups:
    - platform.kubevirt-ui.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedvms
  sideEffects: None
