"""Pydantic models."""

from app.models.cluster import ClusterStatusResponse, NodeListResponse, NodeResponse
from app.models.namespace import NamespaceListResponse, NamespaceResponse
from app.models.network import (
    IPLease,
    NetworkOverview,
    NodeNetworkInfo,
    ProviderNetworkCreate,
    ProviderNetworkResponse,
    ReserveIPRequest,
    ReservedIP,
    SubnetCreate,
    SubnetDetail,
    SubnetResponse,
    SubnetStatistics,
    VlanCreate,
    VlanResponse,
)
from app.models.storage import (
    DataVolumeCreateRequest,
    DataVolumeListResponse,
    DataVolumeResponse,
    PVCListResponse,
    PVCResponse,
    StorageClassListResponse,
    StorageClassResponse,
)
from app.models.vm import (
    VMCreateRequest,
    VMDiskConfig,
    VMListResponse,
    VMNetworkConfig,
    VMResponse,
    VMStatusResponse,
)

__all__ = [
    "ClusterStatusResponse",
    "DataVolumeCreateRequest",
    "DataVolumeListResponse",
    "DataVolumeResponse",
    "IPLease",
    "NamespaceListResponse",
    "NamespaceResponse",
    "NetworkOverview",
    "NodeListResponse",
    "NodeNetworkInfo",
    "NodeResponse",
    "ProviderNetworkCreate",
    "ProviderNetworkResponse",
    "PVCListResponse",
    "PVCResponse",
    "ReserveIPRequest",
    "ReservedIP",
    "StorageClassListResponse",
    "StorageClassResponse",
    "SubnetCreate",
    "SubnetDetail",
    "SubnetResponse",
    "SubnetStatistics",
    "VlanCreate",
    "VlanResponse",
    "VMCreateRequest",
    "VMDiskConfig",
    "VMListResponse",
    "VMNetworkConfig",
    "VMResponse",
    "VMStatusResponse",
]
