"""A talosconfig for the tenant, issued from the tenant's own Talos CA.

R1 was "the only way to look at a Talos node is an SSH crutch", and it is not
a small gap: the entire T22 diagnosis — is this node stuck on its clock or on
something else — needed `talosctl time` and could not run, so it went through
the guest console instead. The console answered that one; it will not answer
the next.

There is no CABPT secret to take a client certificate from — the machine
configs here are rendered by us, not generated by the bootstrap provider — so
the certificate is minted against the CA cert-manager already issues for the
CSR signer. Talos authorises by the certificate's **Organization**: `os:admin`
is full access, and that is what a `talosctl` client needs.

Short-lived on purpose. This is a diagnostic credential handed to a person, so
it expires by itself rather than relying on anyone to revoke it — Talos has no
revocation to speak of.
"""

from __future__ import annotations

import base64
import datetime
import logging
from typing import Any

import yaml
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.x509.oid import NameOID
from fastapi import HTTPException

logger = logging.getLogger(__name__)

TALOS_APID_PORT = 50000

# `os:admin` is the Organization Talos reads for full access; the common name
# is only a label in the logs. Read-only would be `os:reader`.
TALOS_ADMIN_ORG = "os:admin"

DEFAULT_TTL_HOURS = 24


def _load_ca(secret_data: dict[str, str]) -> tuple[x509.Certificate, Any]:
    """The CA certificate and its key, from the cert-manager TLS secret.

    `tls.crt` is the CA's own certificate here — cert-manager writes the issued
    certificate under that key even when the certificate *is* a CA, and
    `ca.crt` is the chain it was issued by. Taking `ca.crt` would sign with the
    self-signed root above it, and every node would reject the result.
    """
    for field in ("tls.crt", "tls.key"):
        if field not in secret_data:
            raise HTTPException(
                status_code=500,
                detail=(
                    f"The tenant's Talos CA secret has no {field!r} — it was "
                    "not issued by cert-manager, or the chain was replaced by "
                    "hand."
                ),
            )

    # Decoding and parsing are separate failures from a missing field, and a
    # secret that is present but unusable is the more confusing of the two: it
    # would otherwise surface as a raw base64 or ASN.1 error with nothing
    # naming the object it came from.
    try:
        crt = base64.b64decode(secret_data["tls.crt"])
        key = base64.b64decode(secret_data["tls.key"])
        return (
            x509.load_pem_x509_certificate(crt),
            serialization.load_pem_private_key(key, password=None),
        )
    except Exception as e:  # noqa: BLE001 — any decode/parse failure reads alike
        raise HTTPException(
            status_code=500,
            detail=(
                "The tenant's Talos CA secret could not be read as a "
                f"certificate and key ({type(e).__name__}). It is present but "
                "not what cert-manager writes."
            ),
        ) from e


def issue_client_certificate(
    secret_data: dict[str, str], *, common_name: str, ttl_hours: int = DEFAULT_TTL_HOURS,
) -> tuple[str, str, str]:
    """Sign an `os:admin` client certificate. Returns (ca_pem, crt_pem, key_pem)."""
    ca_cert, ca_key = _load_ca(secret_data)

    client_key = ed25519.Ed25519PrivateKey.generate()
    now = datetime.datetime.now(datetime.timezone.utc)

    cert = (
        x509.CertificateBuilder()
        .subject_name(x509.Name([
            x509.NameAttribute(NameOID.COMMON_NAME, common_name),
            # The field Talos actually authorises on.
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, TALOS_ADMIN_ORG),
        ]))
        .issuer_name(ca_cert.subject)
        .public_key(client_key.public_key())
        .serial_number(x509.random_serial_number())
        # A minute of leeway: a node whose clock is a few seconds ahead would
        # otherwise reject a certificate issued this instant — and a skewed
        # clock is exactly the situation this credential exists to diagnose.
        .not_valid_before(now - datetime.timedelta(minutes=1))
        .not_valid_after(now + datetime.timedelta(hours=ttl_hours))
        .add_extension(
            x509.BasicConstraints(ca=False, path_length=None), critical=True,
        )
        .add_extension(
            x509.KeyUsage(
                digital_signature=True, content_commitment=False,
                key_encipherment=False, data_encipherment=False,
                key_agreement=False, key_cert_sign=False, crl_sign=False,
                encipher_only=False, decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(
            x509.ExtendedKeyUsage([x509.ExtendedKeyUsageOID.CLIENT_AUTH]),
            critical=False,
        )
        .sign(private_key=ca_key, algorithm=None)   # Ed25519 signs without one
    )

    return (
        ca_cert.public_bytes(serialization.Encoding.PEM).decode(),
        cert.public_bytes(serialization.Encoding.PEM).decode(),
        client_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        ).decode(),
    )


def build_talosconfig(
    tenant: str, *, nodes: list[str], ca_pem: str, crt_pem: str, key_pem: str,
) -> str:
    """The file `talosctl --talosconfig` reads.

    `endpoints` and `nodes` are the worker addresses, not the tenant's
    control-plane VIP: talosctl speaks to apid on each machine (`:50000`), and
    the Kubernetes control plane is a different thing entirely — Kamaji runs it
    as pods and it has no Talos API at all.
    """
    b64 = lambda s: base64.b64encode(s.encode()).decode()  # noqa: E731
    return yaml.safe_dump(
        {
            "context": tenant,
            "contexts": {
                tenant: {
                    # Two distinct lists on purpose. Handing yaml the same
                    # object twice makes it emit an anchor and an alias
                    # (`endpoints: &id001` / `nodes: *id001`) — valid YAML that
                    # a hand-read file should never contain, and one more thing
                    # for a parser on the other side to get wrong.
                    "endpoints": list(nodes),
                    "nodes": list(nodes),
                    "ca": b64(ca_pem),
                    "crt": b64(crt_pem),
                    "key": b64(key_pem),
                },
            },
        },
        default_flow_style=False, sort_keys=False,
    )
