"""A talosconfig from the page, so a Talos node can be asked anything at all.

R1 was not a convenience gap. The whole T22 diagnosis — is this node held by
its clock or by something else — needed `talosctl time`, could not run, and
went through the guest console instead. The console answered that one; it will
not answer the next.

There is no CABPT secret to lift a client certificate from, because the
machine configs here are rendered by us rather than generated by the bootstrap
provider. So the certificate is minted against the CA cert-manager already
issues for the CSR signer, and Talos authorises it by its Organization —
`os:admin` is full access.

Measured end to end on `t8` from a pod inside its VPC:

    talosctl version   Server NODE 10.200.24.10, Enabled: RBAC
    talosctl time      NODE-TIME within 12ms of the server it asked
"""

import base64
import datetime

import pytest
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.x509.oid import NameOID
from fastapi import HTTPException

from app.api.v1.tenants_talosconfig import (
    TALOS_ADMIN_ORG,
    build_talosconfig,
    issue_client_certificate,
)


def _ca_secret() -> dict[str, str]:
    """A cert-manager-shaped TLS secret holding an Ed25519 CA."""
    key = ed25519.Ed25519PrivateKey.generate()
    now = datetime.datetime.now(datetime.timezone.utc)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "t-talos-ca")])
    cert = (
        x509.CertificateBuilder()
        .subject_name(name).issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(hours=1))
        .not_valid_after(now + datetime.timedelta(days=3650))
        .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
        .sign(private_key=key, algorithm=None)
    )
    b64 = lambda b: base64.b64encode(b).decode()  # noqa: E731
    return {
        "tls.crt": b64(cert.public_bytes(serialization.Encoding.PEM)),
        "tls.key": b64(key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )),
        "ca.crt": b64(cert.public_bytes(serialization.Encoding.PEM)),
    }


class TestTheCertificateTalosWillAccept:
    def test_the_organization_is_what_grants_access(self) -> None:
        """Talos reads O, not CN. A certificate with the right common name and
        no organization authenticates and is then refused everything."""
        _, crt_pem, _ = issue_client_certificate(_ca_secret(), common_name="me@t")
        cert = x509.load_pem_x509_certificate(crt_pem.encode())

        orgs = [a.value for a in
                cert.subject.get_attributes_for_oid(NameOID.ORGANIZATION_NAME)]
        assert orgs == [TALOS_ADMIN_ORG]

    def test_it_is_signed_by_the_tenant_ca_and_verifies_against_it(self) -> None:
        secret = _ca_secret()
        ca_pem, crt_pem, _ = issue_client_certificate(secret, common_name="me@t")

        ca = x509.load_pem_x509_certificate(ca_pem.encode())
        cert = x509.load_pem_x509_certificate(crt_pem.encode())

        assert cert.issuer == ca.subject
        # Raises if the signature does not check out.
        ca.public_key().verify(cert.signature, cert.tbs_certificate_bytes)

    def test_the_ca_returned_is_the_ca_that_signed(self) -> None:
        """`tls.crt` is the CA's own certificate; `ca.crt` is the root above
        it. Returning the wrong one hands out a file every node rejects."""
        secret = _ca_secret()
        ca_pem, _, _ = issue_client_certificate(secret, common_name="me@t")

        assert ca_pem.strip() == base64.b64decode(secret["tls.crt"]).decode().strip()

    def test_it_is_a_client_certificate_and_not_a_CA(self) -> None:
        _, crt_pem, _ = issue_client_certificate(_ca_secret(), common_name="me@t")
        cert = x509.load_pem_x509_certificate(crt_pem.encode())

        assert cert.extensions.get_extension_for_class(
            x509.BasicConstraints).value.ca is False
        assert x509.ExtendedKeyUsageOID.CLIENT_AUTH in cert.extensions\
            .get_extension_for_class(x509.ExtendedKeyUsage).value

    def test_it_expires_by_itself(self) -> None:
        """Talos has no revocation worth relying on, so the lifetime is the
        control — this is a credential handed to a person."""
        _, crt_pem, _ = issue_client_certificate(
            _ca_secret(), common_name="me@t", ttl_hours=24)
        cert = x509.load_pem_x509_certificate(crt_pem.encode())

        span = cert.not_valid_after_utc - cert.not_valid_before_utc
        assert datetime.timedelta(hours=23) < span <= datetime.timedelta(hours=25)

    def test_it_is_valid_a_minute_ago(self) -> None:
        """A node whose clock runs slightly ahead would reject a certificate
        issued this instant — and a skewed clock is exactly what this
        credential is for."""
        _, crt_pem, _ = issue_client_certificate(_ca_secret(), common_name="me@t")
        cert = x509.load_pem_x509_certificate(crt_pem.encode())

        assert cert.not_valid_before_utc < datetime.datetime.now(datetime.timezone.utc)

    def test_a_secret_without_a_key_says_so(self) -> None:
        with pytest.raises(HTTPException) as e:
            issue_client_certificate({"tls.crt": "x"}, common_name="me@t")

        assert e.value.status_code == 500
        assert "tls.key" in e.value.detail

    def test_a_secret_that_is_present_but_unreadable_says_that_instead(self) -> None:
        """The more confusing of the two failures: without this it surfaces as
        a raw base64 or ASN.1 error with nothing naming the object it came
        from."""
        secret = _ca_secret()
        secret["tls.key"] = "bm90LWEta2V5"      # valid base64, not a key

        with pytest.raises(HTTPException) as e:
            issue_client_certificate(secret, common_name="me@t")

        assert e.value.status_code == 500
        assert "not what cert-manager writes" in e.value.detail


class TestTheFileTalosctlReads:
    def test_endpoints_and_nodes_are_the_machines(self) -> None:
        """Not the tenant's control-plane VIP: talosctl speaks to apid on each
        machine, and the Kubernetes control plane here is Kamaji pods with no
        Talos API at all."""
        import yaml

        cfg = yaml.safe_load(build_talosconfig(
            "t8", nodes=["10.200.24.10"], ca_pem="A", crt_pem="B", key_pem="C"))
        ctx = cfg["contexts"]["t8"]

        assert ctx["endpoints"] == ["10.200.24.10"]
        assert ctx["nodes"] == ["10.200.24.10"]
        assert cfg["context"] == "t8"

    def test_the_material_is_base64(self) -> None:
        import yaml

        cfg = yaml.safe_load(build_talosconfig(
            "t8", nodes=["1.2.3.4"], ca_pem="ca-pem", crt_pem="crt-pem",
            key_pem="key-pem"))
        ctx = cfg["contexts"]["t8"]

        assert base64.b64decode(ctx["ca"]).decode() == "ca-pem"
        assert base64.b64decode(ctx["crt"]).decode() == "crt-pem"
        assert base64.b64decode(ctx["key"]).decode() == "key-pem"

    def test_it_carries_no_yaml_anchors(self) -> None:
        """Handing yaml the same list twice emits `endpoints: &id001` and
        `nodes: *id001` — valid, and not something a file a human reads and a
        third-party parser consumes should contain."""
        out = build_talosconfig(
            "t8", nodes=["1.2.3.4"], ca_pem="a", crt_pem="b", key_pem="c")

        assert "&id" not in out and "*id" not in out
