#!/usr/bin/env python3
"""Generate the operator's chart templates from the operator's own sources.

The CRDs and the manager ClusterRole are produced by kubebuilder from markers in
the Go code. Copying them into the chart by hand means two records of one fact,
and the copy is the one that goes stale — quietly, because a chart that installs
last year's schema still installs.

So they are generated, and a test regenerates them and refuses a diff.

    hack/sync-operator-chart.py [--check]
"""

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CRD_DIR = ROOT / "operator/config/crd/bases"
ROLE = ROOT / "operator/config/rbac/role.yaml"
OUT = ROOT / "helm/kubevirt-ui/templates"

BANNER = (
    "# Generated by hack/sync-operator-chart.py from {source}.\n"
    "# Do not edit: the markers in the operator's Go code are the source, and a\n"
    "# hand-edit here is a second record of the same fact that nothing compares.\n"
)


def crds() -> str:
    parts = [BANNER.format(source="operator/config/crd/bases")]
    parts.append("{{- if and .Values.operator.enabled .Values.operator.crds.install }}\n")
    for path in sorted(CRD_DIR.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        # Kept on uninstall. These hold the tenants, the networks and the VMs;
        # helm uninstall removing the definitions would cascade-delete every
        # object described by them, which is not what uninstalling a UI means.
        meta = doc.setdefault("metadata", {})
        meta.setdefault("annotations", {})["helm.sh/resource-policy"] = "keep"
        parts.append("---\n" + yaml.safe_dump(doc, sort_keys=False, width=10**6))
    parts.append("{{- end }}\n")
    return "".join(parts)


def rbac() -> str:
    role = yaml.safe_load(ROLE.read_text())
    body = {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "ClusterRole",
        "metadata": {"name": "{{ .Release.Name }}-operator-manager"},
        "rules": role["rules"],
    }
    return (
        BANNER.format(source="operator/config/rbac/role.yaml")
        + "{{- if .Values.operator.enabled }}\n"
        + "---\n"
        + yaml.safe_dump(body, sort_keys=False, width=10**6)
        + "{{- end }}\n"
    )


def main() -> int:
    wanted = {
        OUT / "operator-crds.yaml": crds(),
        OUT / "operator-manager-role.yaml": rbac(),
    }
    check = "--check" in sys.argv
    drifted = []
    for path, text in wanted.items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        drifted.append(path.relative_to(ROOT))
        if not check:
            path.write_text(text)
    if check and drifted:
        print("out of sync: " + ", ".join(str(p) for p in drifted), file=sys.stderr)
        return 1
    print("synced" if not check else "in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
