---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datasources
  - datavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubevirt-ui.io
  resources:
  - managedimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubevirt-ui.io
  resources:
  - managedimages/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kubevirt-ui.io
  resources:
  - managedimages/status
  verbs:
  - get
  - patch
  - update
