---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - limitranges
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - talosconfigtemplates
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datasources
  - datavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes/source
  verbs:
  - create
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clone.kubevirt.io
  resources:
  - virtualmachineclones
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machinedeployments
  - machinehealthchecks
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kamajicontrolplanes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrnodestates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kubevirtclusters
  - kubevirtmachinetemplates
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeovn.io
  resources:
  - ovn-eips
  - ovn-snat-rules
  - provider-networks
  - subnets
  - vlans
  - vpc-dnses
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstancemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metallb.io
  resources:
  - ipaddresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.kubevirt-ui.io
  resources:
  - announcementpolicies
  - managedimages
  - managednetworkpeerings
  - managednetworks
  - managedtenants
  - managedunderlays
  - managedvmoperations
  - managedvms
  - managedvmtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubevirt-ui.io
  resources:
  - announcementpolicies/status
  - managedimages/status
  - managednetworkpeerings/status
  - managednetworks/status
  - managedtenants/status
  - managedunderlays/status
  - managedvmoperations/status
  - managedvms/status
  - managedvmtemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.kubevirt-ui.io
  resources:
  - managedimages/finalizers
  - managedvms/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.kubevirt.io
  resources:
  - virtualmachinerestores
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - snapshot.kubevirt.io
  resources:
  - virtualmachinesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traefik.io
  resources:
  - ingressroutetcps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
